name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  spm:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: swift build -v
      - run: swift test -v
      - run: swift format lint -r Sources Tests
